### Analyzing Customer Churn in a Telecommunications Company

- dataset link:https://raw.githubusercontent.com/harshbg/Telecom-Churn-Data-Analysis/master/Telecom%20Churn.csv

In [35]:
#Import the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [36]:
# Load the datasets
df = pd.read_csv("./datasets/assignment-06.csv")

print("Training dataset shape:", df.shape)

display(df.head())

Training dataset shape: (3333, 21)

,state,account length,area code,phone number,international plan,voice mail plan,number vmail messages,total day minutes,total day calls,total day charge,...,total eve calls,total eve charge,total night minutes,total night calls,total night charge,total intl minutes,total intl calls,total intl charge,customer service calls,churn
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False

In [37]:
# Explore the dataset
print("Training dataset information:")
df.info()

print("Statistical summary of the training dataset:")
display(df.describe(include='all'))

print("Missing values in the training dataset:")
print(df.isnull().sum())

print("\nDuplicate records:")
print("Training:", df.duplicated().sum())

Training dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   state                   3333 non-null   object
 1   account length          3333 non-null   int64
 2   area code               3333 non-null   int64
 3   phone number            3333 non-null   object
 4   international plan      3333 non-null   object
 5   voice mail plan         3333 non-null   object
 6   number vmail messages   3333 non-null   int64
 7   total day minutes       3333 non-null   float64
 8   total day calls         3333 non-null   int64
 9   total day charge        3333 non-null   float64
 10  total eve minutes       3333 non-null   float64
 11  total eve calls         3333 non-null   int64
 12  total eve charge        3333 non-null   float64
 13  total night minutes     3333 non-null   float64
 14  total night calls       3333 non-null   int64
 15  total night charge      3333 non-null   float64
 16  total intl minutes      3333 non-null   float64
 17  total intl calls        3333 non-null   int64
 18  total intl charge       3333 non-null   float64
 19  customer service calls  3333 non-null   int64
 20  churn                   3333 non-null   bool
dtypes: bool(1), float64(8), int64(8), object(4)
memory usage: 524.2+ KB
Statistical summary of the training dataset:

,state,account length,area code,phone number,international plan,voice mail plan,number vmail messages,total day minutes,total day calls,total day charge,...,total eve calls,total eve charge,total night minutes,total night calls,total night charge,total intl minutes,total intl calls,total intl charge,customer service calls,churn
count,3333,3333.000000,3333.000000,3333,3333,3333,3333.000000,3333.000000,3333.000000,3333.000000,...,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333
unique,51,NaN,NaN,3333,2,2,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
top,WV,NaN,NaN,400-4344,no,no,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
freq,106,NaN,NaN,1,3010,2411,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2850
mean,NaN,101.064806,437.182418,NaN,NaN,NaN,8.099010,179.775098,100.435644,30.562307,...,100.114311,17.083540,200.872037,100.107711,9.039325,10.237294,4.479448,2.764581,1.562856,NaN
std,NaN,39.822106,42.371290,NaN,NaN,NaN,13.688365,54.467389,20.069084,9.259435,...,19.922625,4.310668,50.573847,19.568609,2.275873,2.791840,2.461214,0.753773,1.315491,NaN
min,NaN,1.000000,408.000000,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,23.200000,33.000000,1.040000,0.000000,0.000000,0.000000,0.000000,NaN
25%,NaN,74.000000,408.000000,NaN,NaN,NaN,0.000000,143.700000,87.000000,24.430000,...,87.000000,14.160000,167.000000,87.000000,7.520000,8.500000,3.000000,2.300000,1.000000,NaN
50%,NaN,101.000000,415.000000,NaN,NaN,NaN,0.000000,179.400000,101.000000,30.500000,...,100.000000,17.120000,201.200000,100.000000,9.050000,10.300000,4.000000,2.780000,1.000000,NaN
75%,NaN,127.000000,510.000000,NaN,NaN,NaN,20.000000,216.400000,114.000000,36.790000,...,114.000000,20.000000,235.300000,113.000000,10.590000,12.100000,6.000000,3.270000,2.000000,NaN
max,NaN,243.000000,510.000000,NaN,NaN,NaN,51.000000,350.800000,165.000000,59.640000,...,170.000000,30.910000,395.000000,175.000000,17.770000,20.000000,20.000000,5.400000,9.000000,NaN

Missing values in the training dataset:
state                     0
account length            0
area code                 0
phone number              0
international plan        0
voice mail plan           0
number vmail messages     0
total day minutes         0
total day calls           0
total day charge          0
total eve minutes         0
total eve calls           0
total eve charge          0
total night minutes       0
total night calls         0
total night charge        0
total intl minutes        0
total intl calls          0
total intl charge         0
customer service calls    0
churn                     0
dtype: int64

Duplicate records:
Training: 0

In [38]:
# Handle missing values
df = df.dropna(subset=['churn']).copy()

numeric_cols = df.select_dtypes(include=np.number).columns.tolist()
categorical_cols = df.select_dtypes(include=["object","string"]).columns.tolist()

for col in numeric_cols:
    df[col]=df[col].fillna(df[col].median())

for col in categorical_cols:
    if df[col].isnull().any():
        df[col]=df[col].fillna(df[col].mode()[0])


print("Remaining missing values",df.isnull().sum())

Remaining missing values state                     0
account length            0
area code                 0
phone number              0
international plan        0
voice mail plan           0
number vmail messages     0
total day minutes         0
total day calls           0
total day charge          0
total eve minutes         0
total eve calls           0
total eve charge          0
total night minutes       0
total night calls         0
total night charge        0
total intl minutes        0
total intl calls          0
total intl charge         0
customer service calls    0
churn                     0
dtype: int64

In [39]:
# Remove duplicate records

df = df.drop_duplicates().reset_index(drop=True)
print("Duplicates after cleaning:",df.duplicated().sum())

Duplicates after cleaning: 0

In [40]:
# Remove the inconsistent data
categorical_columns=df.select_dtypes(include=["object","string"]).columns
for col in categorical_columns:
    df[col]=df[col].astype('string').str.strip()

for col in ['International plan','Voice mail plan']:
    if col in df.columns:
        df=df[col].str.lower().map({"yes":"Yes","no":"No"}).fillna(df[col])


if "State" in df.columns:
    df=df["State"].str.upper()

In [41]:
# Convert columns to appropriate data types

#convert numeric columns
for col in numeric_cols:
    df[col]=pd.to_numeric(df[col],errors='coerce')


# Handle any invalid numerical values 
for col in numeric_cols:
    df[col]=df[col].fillna(df[col].median())

# Standardize churn target
df['churn'] = (
    df["churn"].astype(str).str.strip().str.lower()
    .map({"true": True, "false": False, "yes": True, "no": False,
          "1": True, "0": False})
)

df = df.dropna(subset=['churn']).reset_index(drop=True)


print("Updated data types:")
print(df.dtypes)

Updated data types:
state                     string[python]
account length                     int64
area code                          int64
phone number              string[python]
international plan        string[python]
voice mail plan           string[python]
number vmail messages              int64
total day minutes                float64
total day calls                    int64
total day charge                 float64
total eve minutes                float64
total eve calls                    int64
total eve charge                 float64
total night minutes              float64
total night calls                  int64
total night charge               float64
total intl minutes               float64
total intl calls                   int64
total intl charge                float64
customer service calls             int64
churn                               bool
dtype: object

In [42]:
# Detect and handle outliers

outlier_cols = [
    col for col in df.select_dtypes(include=np.number).columns
    if col not in ["area code","churn"]
]

for col in outlier_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    count = ((df[col]<lower)|(df[col]>upper)).sum()
    print(f"{col}:{count} outliers deteted")

    df[col]=df[col].clip(lower,upper)

print("Outlier handling completed.")

account length:18 outliers deteted
number vmail messages:1 outliers deteted
total day minutes:25 outliers deteted
total day calls:23 outliers deteted
total day charge:25 outliers deteted
total eve minutes:24 outliers deteted
total eve calls:20 outliers deteted
total eve charge:24 outliers deteted
total night minutes:30 outliers deteted
total night calls:22 outliers deteted
total night charge:30 outliers deteted
total intl minutes:46 outliers deteted
total intl calls:78 outliers deteted
total intl charge:49 outliers deteted
customer service calls:267 outliers deteted
Outlier handling completed.

In [43]:
# Perform feature engineering

df["total minutes"] = (
    df["total day minutes"]
    + df["total eve minutes"]
    + df["total night minutes"]
    + df["total intl minutes"]
)

df["total calls"] = (
    df["total day calls"]
    + df["total eve calls"]
    + df["total night calls"]
    + df["total intl calls"]
)

df["total charges"] = (
    df["total day charge"]
    + df["total eve charge"]
    + df["total night charge"]
    + df["total intl charge"]
)

display(df[["total minutes", "total calls", "total charges", "churn"]].head())

   total minutes  total calls  total charges  churn
0         717.20        303.0          75.56  False
1         625.20        332.0          59.24  False
2         539.40        333.0          62.29  False
3         566.45        255.0          66.94  False
4         512.00        359.0          52.09  False

In [44]:
# Scale features
excluded_cols= ['churn','state','international plan','voice main plan','area code']

scale_cols=[col for col in df.select_dtypes(include=np.number).columns if col not in excluded_cols]


scaler = StandardScaler()
df[scale_cols] = scaler.fit_transform(df[scale_cols])

print("Numerical features scaled.")
display(df[scale_cols].head())

Numerical features scaled.

,account length,number vmail messages,total day minutes,total day calls,total day charge,total eve minutes,total eve calls,total eve charge,total night minutes,total night calls,total night charge,total intl minutes,total intl calls,total intl charge,customer service calls,total minutes,total calls,total charges
0,0.681078,1.234989,1.575128,0.479660,1.575396,-0.071627,-0.057407,-0.071441,0.875492,-0.468006,0.874825,-0.093573,-0.627131,-0.094399,-0.430249,1.403749,-0.062359,1.543208
1,0.151286,1.308059,-0.336439,1.134217,-0.336715,-0.109330,0.145067,-0.108793,1.069062,0.149253,1.069958,1.266421,-0.627131,1.267378,-0.430249,0.372994,0.786272,-0.021283
2,0.908132,-0.591778,1.174346,0.681062,1.174505,-1.583717,0.499397,-1.584225,-0.762868,0.200691,-0.761631,0.715072,0.253150,0.709049,-1.333569,-0.588297,0.815535,0.271101
3,-0.428963,-0.591778,2.208623,-1.484012,2.208783,-2.727707,-0.614211,-2.728151,-0.078389,-0.570882,-0.078665,-1.343298,1.133431,-1.347234,0.473071,-0.285232,-1.466989,0.716866
4,-0.656017,-0.591778,-0.242246,0.630711,-0.242196,-1.045953,1.106820,-1.044945,-0.277945,1.075140,-0.278233,-0.056817,-0.627131,-0.053546,1.376390,-0.895282,1.576376,-0.706706

In [45]:
# Spilt in train and test

X = df.drop(columns=["churn"])
y = df["churn"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training features:", X_train.shape)
print("Testing features:", X_test.shape)
print("Training targets:", y_train.shape)
print("Testing targets:", y_test.shape)

Training features: (2666, 23)
Testing features: (667, 23)
Training targets: (2666,)
Testing targets: (667,)

In [46]:
# Export to clean csv
df.to_csv("./outputs/assingment-06-op.csv",index=False)

# Export the train and test datasets
X_train.to_csv("./outputs/assingment-06-op-train.csv", index=False)
X_test.to_csv("./outputs/assingment-06-op-test.csv", index=False)
y_train.to_csv("./outputs/assingment-06-op-train-targets.csv", index=False)
y_test.to_csv("./outputs/assingment-06-op-test-targets.csv", index=False)


print("Cleaned dataset and train-test splits exported successfully.")

Cleaned dataset and train-test splits exported successfully.